kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebook-storage
  annotations:
      pv.beta.kubernetes.io/gid: "100"
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: notebook-client
  labels:
    app: notebook-client
spec:
  serviceAccountName: spark
  securityContext:
    fsGroup: 100 
  volumes:
    - name: notebook-storage
      persistentVolumeClaim:
       claimName: notebook-storage
  containers:
    - name: notebook
      image: jamesrcounts/variantspark-notebook
      ports:
        - containerPort: 8888
          name: "notebook-server"
      volumeMounts:
        - mountPath: "/home/jovyan/work"
          name: notebook-storage
---
kind: Service
apiVersion: v1
metadata:
  name: notebook-client
spec:
  selector:
    app: notebook-client
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: LoadBalancer
