#!/bin/bash

set -e

function fatal_error () {
	echo "ERROR: $1" 1>&2
	exit 1
}

MASTER=https://api-kops1-k8s-local-u6p60a-1741966285.us-west-1.elb.amazonaws.com
INPUT_BUCKET=variant-spark-k-storage20180615052509001100000001

[[ $(type -P "spark-submit") ]] || fatal_error  "\`spark-submit\` cannot be found. Please make sure it's on your PATH."

spark-submit \
    --class au.csiro.variantspark.cli.VariantSparkApp \
    --driver-class-path ./conf \
    --master k8s://${MASTER}:443 \
    --deploy-mode cluster \
    --name VariantSpark \
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
    --conf spark.executor.instances=6 \
    --conf spark.kubernetes.container.image=jamesrcounts/variantspark:001 \
    --jars http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.3/hadoop-aws-2.7.3.jar,http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar,http://central.maven.org/maven2/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar \
    local:///opt/spark/jars/variant-spark_2.11-0.2.0-SNAPSHOT-all.jar importance \
        -if s3a://${INPUT_BUCKET}/input/chr22_1000.vcf \
        -ff s3a://${INPUT_BUCKET}/input/chr22-labels.csv \
        -fc 22_16051249 \
        -v \
        -rn 500 \
        -rbs 20 \
        -ro "$@"
